//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPark
{
    using System;
    using System.Collections.Generic;

    public partial class Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driver()
        {
            this.Bus = new HashSet<Bus>();
        }

        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public System.DateTime DateOfBith { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Experience { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Bus { get; set; }
        public override string ToString()
        {
            return LastName + " " + FirstName[0] + ".";
        }

        public object Clone()
        {
            return new Driver
            {
                Id = this.Id,
                LastName = this.LastName,
                FirstName = this.FirstName,
                DateOfBith = this.DateOfBith,
                Address = this.Address,
                Phone = this.Phone,
                Experience = this.Experience,
                Bus = this.Bus
            };
        }
    }
}
