//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPark
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public int Id { get; set; }
        public string Brand { get; set; }
        public int IdTypeBus { get; set; }
        public int IdCondition { get; set; }
        public int NumberOfSeats { get; set; }
        public string GovernmentNumber { get; set; }
        public Nullable<int> IdDriver { get; set; }
    
        public virtual Condition Condition { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual TypeBus TypeBus { get; set; }

        public object Clone()
        {
            Condition condition = new Condition
            {
                Id = this.Condition.Id,
                Name = this.Condition.Name
            };

            Driver driver = new Driver
            {
                Id = this.Driver.Id,
                Address = this.Driver.Address,
                DateOfBith = this.Driver.DateOfBith,
                Experience = this.Driver.Experience,
                FirstName = this.Driver.FirstName,
                LastName = this.Driver.LastName,
                Phone = this.Driver.Phone
            };

            TypeBus typeBus = new TypeBus
            {
                Id = this.TypeBus.Id,
                Name = this.TypeBus.Name
            };

            return new Bus
            {
                Id = this.Id,
                Brand = this.Brand,
                IdTypeBus = this.IdTypeBus,
                IdCondition = this.IdCondition,
                IdDriver = this.IdDriver,
                NumberOfSeats = this.NumberOfSeats,
                GovernmentNumber = this.GovernmentNumber,
                Condition = condition,
                Driver = driver,
                TypeBus = typeBus
            };
        }
    }
}
