//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPark
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public int Id { get; set; }
        public string Brand { get; set; }
        public int IdTypeBus { get; set; }
        public int IdCondition { get; set; }
        public int NumberOfSeats { get; set; }
        public string GovernmentNumber { get; set; }
        public int IdDriver { get; set; }
    
        public virtual Condition Condition { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual TypeBus TypeBus { get; set; }
    }
}
