//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarPark
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public System.DateTime DateOfBith { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Experience { get; set; }
        public Nullable<int> IdBus { get; set; }
    
        public virtual Bus Bus { get; set; }
    }
}
